spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
#          访问方法http://127:0:0:1:88/?url=baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq
        - id: qq_route
          uri: https://www.google.com
          predicates:
              - Query=url, google